import { describe, it, expect } from 'vitest';
import { ReefReader, DataType, Codec } from '../src/index.js';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

/**
 * Cross-language test: synthetic fixture with ALP + GORILLA + PONGO on same data.
 * Generated by GorilaPongoFixtureGenerator.java (Random(42), 100 rows, 2dp).
 */
describe('Gorilla/Pongo synthetic fixture (Java → TS)', () => {
  const FIXTURE = join(__dirname, 'fixtures', 'gorilla-pongo.reef');
  const data = existsSync(FIXTURE) ? new Uint8Array(readFileSync(FIXTURE)) : null;

  it('should have fixture file', () => {
    expect(data).not.toBeNull();
  });

  it('should parse header and column descriptors', () => {
    if (!data) return;
    const r = new ReefReader(data);
    expect(r.seriesRowCount).toBe(100);
    expect(r.seriesColumns).toHaveLength(4);
    expect(r.seriesColumns[2]).toMatchObject({ name: 'close_gorilla', codec: Codec.GORILLA });
    expect(r.seriesColumns[3]).toMatchObject({ name: 'close_pongo', codec: Codec.PONGO });
  });

  it('should decode all three codecs to identical values', () => {
    if (!data) return;
    const r = new ReefReader(data);
    const alp = r.readSeriesDouble('close_alp');
    const gorilla = r.readSeriesDouble('close_gorilla');
    const pongo = r.readSeriesDouble('close_pongo');
    expect(alp).toHaveLength(100);
    for (let i = 0; i < 100; i++) {
      expect(gorilla[i]).toBe(alp[i]);
      expect(pongo[i]).toBe(alp[i]);
    }
  });

  it('should decode known reference values', () => {
    if (!data) return;
    const r = new ReefReader(data);
    const close = r.readSeriesDouble('close_alp');
    expect(close[0]).toBeCloseTo(65011.42, 2);
    expect(close[1]).toBeCloseTo(65020.61, 2);
    expect(close[99]).toBeCloseTo(64966.73, 2);
  });
});

/**
 * Real-world test: BTC/USDT ticker data converted with --best (mixed codecs).
 * 3,591 rows, columns use ALP and PONGO depending on data characteristics.
 */
describe('BTC/USDT real fixture with mixed codecs', () => {
  const FIXTURE = join(__dirname, 'fixtures', 'btc-usdt-best.reef');
  const data = existsSync(FIXTURE) ? new Uint8Array(readFileSync(FIXTURE)) : null;

  it('should have fixture file', () => {
    expect(data).not.toBeNull();
  });

  it('should parse header', () => {
    if (!data) return;
    const r = new ReefReader(data);
    expect(r.seriesRowCount).toBe(3591);
    expect(r.seriesColumns).toHaveLength(11);
  });

  it('should have mixed codecs (ALP and PONGO)', () => {
    if (!data) return;
    const r = new ReefReader(data);
    const codecs = new Set(r.seriesColumns.map(c => c.codec));
    expect(codecs.has(Codec.DELTA_VARINT)).toBe(true);
    expect(codecs.has(Codec.ALP)).toBe(true);
    expect(codecs.has(Codec.PONGO)).toBe(true);
  });

  it('should decode timestamps', () => {
    if (!data) return;
    const r = new ReefReader(data);
    const ts = r.readSeriesLong('t');
    expect(ts).toHaveLength(3591);
    expect(ts[0]).toBe(1775584800005);
    expect(ts[ts.length - 1]).toBe(1775588399002);
  });

  it('should decode PONGO-encoded close prices', () => {
    if (!data) return;
    const r = new ReefReader(data);
    expect(r.getSeriesColumn('cls').codec).toBe(Codec.PONGO);
    const cls = r.readSeriesDouble('cls');
    expect(cls).toHaveLength(3591);
    expect(cls[0]).toBeCloseTo(68705.81, 2);
    expect(cls[1]).toBeCloseTo(68705.82, 2);
    expect(cls[cls.length - 1]).toBeCloseTo(68442.52, 2);
  });

  it('should decode PONGO-encoded bid prices', () => {
    if (!data) return;
    const r = new ReefReader(data);
    expect(r.getSeriesColumn('bid').codec).toBe(Codec.PONGO);
    const bid = r.readSeriesDouble('bid');
    expect(bid).toHaveLength(3591);
    expect(bid[0]).toBeCloseTo(68705.81, 2);
  });

  it('should decode ALP-encoded volume', () => {
    if (!data) return;
    const r = new ReefReader(data);
    expect(r.getSeriesColumn('vol').codec).toBe(Codec.ALP);
    const vol = r.readSeriesDouble('vol');
    expect(vol).toHaveLength(3591);
    expect(vol[0]).toBeGreaterThan(0);
  });

  it('should decode PONGO-encoded open prices', () => {
    if (!data) return;
    const r = new ReefReader(data);
    expect(r.getSeriesColumn('opn').codec).toBe(Codec.PONGO);
    const opn = r.readSeriesDouble('opn');
    expect(opn).toHaveLength(3591);
    expect(opn[0]).toBeCloseTo(69574.62, 2);
  });

  it('should decode all columns without error', () => {
    if (!data) return;
    const r = new ReefReader(data);
    for (const col of r.seriesColumns) {
      if (col.dataType === DataType.LONG) {
        expect(() => r.readSeriesLong(col.name)).not.toThrow();
      } else if (col.dataType === DataType.DOUBLE) {
        expect(() => r.readSeriesDouble(col.name)).not.toThrow();
      }
    }
  });
});
