import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { join } from 'path';
import { LastraReader } from '../src/reader.js';

const FIXTURE = join(__dirname, 'fixtures', 'row-groups.lastra');

describe('Row groups (Java writer → TS reader)', () => {
  it('should have fixture file', () => {
    expect(existsSync(FIXTURE)).toBe(true);
  });

  it('should parse row group count and total rows', () => {
    const buf = readFileSync(FIXTURE);
    const r = new LastraReader(buf);

    // 10000 rows / 3600 RG size = 3 RGs (3600 + 3600 + 2800)
    expect(r.seriesRowCount).toBe(10000);
    expect(r.rowGroupCount).toBe(3);
    expect(r.seriesColumns.length).toBe(2);
    expect(r.seriesColumns[0].name).toBe('ts');
    expect(r.seriesColumns[1].name).toBe('close');
  });

  it('should have correct per-RG stats', () => {
    const buf = readFileSync(FIXTURE);
    const r = new LastraReader(buf);

    const rg0 = r.rowGroupStats(0)!;
    expect(rg0.rowCount).toBe(3600);
    expect(rg0.tsMin).toBe(1711152000000);
    expect(rg0.tsMax).toBe(1711152000000 + 3599 * 1000);

    const rg1 = r.rowGroupStats(1)!;
    expect(rg1.rowCount).toBe(3600);
    expect(rg1.tsMin).toBe(1711152000000 + 3600 * 1000);

    const rg2 = r.rowGroupStats(2)!;
    expect(rg2.rowCount).toBe(2800);
    expect(rg2.tsMax).toBe(1711152000000 + 9999 * 1000);
  });

  it('should read a single row group selectively', () => {
    const buf = readFileSync(FIXTURE);
    const r = new LastraReader(buf);

    const rg1Close = r.readRowGroupDouble(1, 'close');
    expect(rg1Close.length).toBe(3600);
    // Values should be valid prices (~65000)
    expect(rg1Close[0]).toBeGreaterThan(64000);
    expect(rg1Close[0]).toBeLessThan(66000);
  });

  it('should read full series concatenating all RGs', () => {
    const buf = readFileSync(FIXTURE);
    const r = new LastraReader(buf);

    const allTs = r.readSeriesLong('ts');
    expect(allTs.length).toBe(10000);
    // First and last timestamps
    expect(allTs[0]).toBe(1711152000000);
    expect(allTs[9999]).toBe(1711152000000 + 9999 * 1000);
    // Monotonically increasing
    for (let i = 1; i < allTs.length; i++) {
      expect(allTs[i]).toBeGreaterThan(allTs[i - 1]);
    }

    const allClose = r.readSeriesDouble('close');
    expect(allClose.length).toBe(10000);
  });

  it('should filter RGs by temporal range', () => {
    const buf = readFileSync(FIXTURE);
    const r = new LastraReader(buf);

    // Query: rows 4000-5000 → only RG 1 (3600-7199)
    const queryFrom = 1711152000000 + 4000 * 1000;
    const queryTo = 1711152000000 + 5000 * 1000;

    let matched = 0;
    for (let i = 0; i < r.rowGroupCount; i++) {
      const stats = r.rowGroupStats(i)!;
      if (stats.tsMax >= queryFrom && stats.tsMin <= queryTo) {
        matched++;
      }
    }
    expect(matched).toBe(1);
  });

  it('should verify CRC32 per row group', () => {
    const buf = readFileSync(FIXTURE);
    const r = new LastraReader(buf);
    expect(r.hasChecksums).toBe(true);

    // Reading should not throw (CRC verified internally)
    for (let rg = 0; rg < r.rowGroupCount; rg++) {
      r.readRowGroupLong(rg, 'ts');
      r.readRowGroupDouble(rg, 'close');
    }
  });
});

// Mirrors lastra-java's testMultipleWriteSeriesCallsAccumulate (0.8.2 writer fix).
// Streaming-append: K calls of writeSeries(rgSize, ...) → K row groups whose
// concatenation equals the total. Verifies the TS reader handles the multi-call
// pattern correctly: footer's seriesRowCount must be the SUM, full-series reads
// must size the result buffer to that sum and return all rgCount*rgSize values.
// (Files produced by buggy lastra-java ≤0.8.1 record only the last call's count
// in the footer; this regression fixture is generated by 0.8.2+, so the TS
// reader's `new Float64Array(this.seriesRowCount)` sizing path stays valid.)
const MULTI_WRITE_FIXTURE = join(__dirname, 'fixtures', 'multi-write.lastra');

describe('Multiple writeSeries() calls (Java 0.8.2+ → TS reader)', () => {
  const rgSize = 100;
  const rgCount = 4;
  const t0 = 1_700_000_000_000;
  const hourMs = 3_600_000;
  const totalRows = rgSize * rgCount;

  it('should have fixture file', () => {
    expect(existsSync(MULTI_WRITE_FIXTURE)).toBe(true);
  });

  it('should report seriesRowCount as the SUM across writeSeries() calls', () => {
    const buf = readFileSync(MULTI_WRITE_FIXTURE);
    const r = new LastraReader(buf);
    expect(r.rowGroupCount).toBe(rgCount);
    expect(r.seriesRowCount).toBe(totalRows);
    expect(r.seriesColumns.map((c) => c.name)).toEqual(['ts', 'v']);
  });

  it('should bind each RG stats to the slice from its own writeSeries() call', () => {
    const buf = readFileSync(MULTI_WRITE_FIXTURE);
    const r = new LastraReader(buf);
    for (let g = 0; g < rgCount; g++) {
      const s = r.rowGroupStats(g)!;
      expect(s.rowCount).toBe(rgSize);
      expect(s.tsMin).toBe(t0 + g * hourMs);
      expect(s.tsMax).toBe(t0 + g * hourMs + (rgSize - 1));
    }
  });

  it('should read the full series concatenating all RGs in order', () => {
    const buf = readFileSync(MULTI_WRITE_FIXTURE);
    const r = new LastraReader(buf);

    const ts = r.readSeriesLong('ts');
    const v = r.readSeriesDouble('v');
    expect(ts.length).toBe(totalRows);
    expect(v.length).toBe(totalRows);
    expect(ts[0]).toBe(t0);
    expect(ts[rgSize]).toBe(t0 + hourMs); // first ts of RG #2
    expect(ts[totalRows - 1]).toBe(t0 + (rgCount - 1) * hourMs + (rgSize - 1));
    expect(v[0]).toBeCloseTo(100.0, 10);
    expect(v[totalRows - 1]).toBeCloseTo(100.0 + (rgCount - 1) + (rgSize - 1) * 0.01, 10);
  });

  it('should read a single RG selectively', () => {
    const buf = readFileSync(MULTI_WRITE_FIXTURE);
    const r = new LastraReader(buf);
    const rg2Ts = r.readRowGroupLong(2, 'ts');
    expect(rg2Ts.length).toBe(rgSize);
    expect(rg2Ts[0]).toBe(t0 + 2 * hourMs);
  });
});
